/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#48645c",
        "surface-bright": "#fef9f0",
        "inverse-surface": "#32302a",
        "tertiary-container": "#1f291e",
        "on-background": "#1d1c16",
        "primary-fixed-dim": "#afcdc4",
        "on-tertiary": "#ffffff",
        "surface": "#fef9f0",
        "on-error": "#ffffff",
        "outline": "#727976",
        "error-container": "#ffdad6",
        "surface-variant": "#e7e2d9",
        "surface-container-high": "#ece8df",
        "tertiary-fixed-dim": "#bfcaba",
        "on-tertiary-fixed": "#151e14",
        "tertiary-fixed": "#dbe6d5",
        "on-secondary-container": "#fffbff",
        "on-primary-fixed-variant": "#314c45",
        "on-surface-variant": "#414846",
        "outline-variant": "#c1c8c5",
        "on-tertiary-fixed-variant": "#3f493d",
        "secondary-container": "#d9381e",
        "on-surface": "#1d1c16",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#869182",
        "primary": "#001511",
        "inverse-on-surface": "#f5f0e7",
        "tertiary": "#0b140b",
        "on-primary-container": "#77938b",
        "background": "#fef9f0",
        "secondary-fixed": "#ffdad3",
        "primary-fixed": "#cae9df",
        "surface-dim": "#ded9d1",
        "on-secondary-fixed": "#3f0300",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e7e2d9",
        "secondary-fixed-dim": "#ffb4a6",
        "on-primary-fixed": "#03201a",
        "inverse-primary": "#afcdc4",
        "primary-container": "#0f2b25",
        "surface-container": "#f2ede4",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#8f1100",
        "surface-container-low": "#f8f3ea",
        "secondary": "#b51d04",
        "on-error-container": "#93000a",
        // Editorial paper extensions from DESIGN.md
        "paper": "#f4efe6",
        "paper-light": "#fbf8f2",
        "ink": "#14181a",
        "muted-ink": "#67625a",
        "hairline": "#ddd5c7",
        "forest": "#0f2b25",
        "forest-soft": "#1b3d35",
        "muted-forest": "#a9b9b2",
        "vermilion": "#d9381e",
        "sage": "#cbd6c6",
        "butter": "#f1dc9a"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "margin": "3rem",
        "margin-mobile": "1.25rem",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "headline-xl": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "headline-xl-mobile": ["Newsreader", "serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-sm": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "body-md": ["1rem", { "lineHeight": "1.5rem", "fontWeight": "400" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.75rem", "fontWeight": "400" }],
        "headline-sm": ["1.25rem", { "lineHeight": "1.625rem", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-md": ["1.75rem", { "lineHeight": "2.125rem", "letterSpacing": "-0.015em", "fontWeight": "500" }],
        "headline-lg": ["2.5rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-lg-mobile": ["1.75rem", { "lineHeight": "2rem", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "headline-xl": ["3.5rem", { "lineHeight": "3.75rem", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-xl-mobile": ["2.25rem", { "lineHeight": "2.5rem", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "label-sm": ["0.6875rem", { "lineHeight": "0.875rem", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "label-md": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.06em", "fontWeight": "500" }],
      }
    }
  },
  plugins: [],
}
